# Generated by Django 2.2.8 on 2020-04-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection_app', '0002_article'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='ArticleS',
        ),
    ]
